### PR TITLE
Improve validate method type

### PR DESCRIPTION
**Pull request by Julinia**

### CODE REVIEW

**Comment by tarunbatra** [comment]
Hi @Julinia, thanks for the contribution.

It's a good attempt to remove some of the ambiguity from the return type of the `validate` method. I'm not very well versed in TypeScript, however I think the updated type inferred will wrong in the cases like:

```js
passwordSchema.validate('password', {});
```
Or, 
```js
passwordSchema.validate('password', { list: false });
```
In the above cases return type will be `boolean` and not `string[]` as indicated in typings.

**Comment by Julinia** [comment]
Hey @tarunbatra , 
I changed typings particularly for {list:true} case.
Thanks for your repo, I am using it!

**Comment by tarunbatra** [comment]
Yes, this looks good to me. I'll get this out with other dependabot PRs soon. Thanks for using it and contributing. :)

**Comment by tarunbatra** [comment]
Deployed with `v5.1.1`. Thanks for the contribution and sorry for the delay!

**Pull request merged**
