### PR TITLE
Improve return types of validate method

### PR DESCRIPTION
**Pull request by rocktimsaikia**
1. Added function overloads to improve the return type of the `verify` class method specifically.

**Before**:
> Used to return the same union type. Which required hacks like `as string[]` in TS.
```sh
validate("password") # Boolean | string[]
validate("password", { list: true }) # Boolean | string[]
validate("password", { details: true }) # Boolean | string[]
```
**After:**
> Now returns single specific type depending on the options provieded. Better DX.
```sh
validate("password") # Boolean
validate("password", { list: true }) # string[]
validate("password", { details: true }) # IDetails[]
```

2. Defined proper interfaces (`IOptions`, `IDetails`) for options and details.

3. Other changes are just auto formatting by prettier plugin.

### CODE REVIEW

**Comment by tarunbatra** [comment]
Hey @rocktimsaikia, thanks for the PR. The change itself looks good to me but I am not enthused about running prettier n the repository. Would you be willing to update the PR with prettier turned off in your code editor?

**Comment by rocktimsaikia** [comment]
@tarunbatra I have removed the unwanted formatted changes.

**Comment by rocktimsaikia** [comment]
@tarunbatra Just a friendly ping.

**Review by tarunbatra — APPROVED** [review]
Thank you!

**Comment by rocktimsaikia** [comment]
@tarunbatra Could you please make a release also for the changes in npm?

**Pull request merged**
